name: CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_and_publish_docker:
    permissions:
      packages: write
      contents: read
    uses: "mikejgray/.github/.github/workflows/publish_docker.yml@patch-2"
    with:
      platforms: linux/amd64,linux/arm64
