name: CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_and_publish_docker:
    permissions:
      packages: write
      contents: read
    uses: "neongeckocom/.github/.github/workflows/publish_docker.yml@TEST_ArmBuilds"
    secrets: inherit
    with:
      platforms: linux/amd64,linux/arm/v8
