name: CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  actions: write
  contents: read

jobs:
  build_and_publish_docker:
    uses: "neongeckocom/.github/.github/workflows/publish_docker.yml@TEST_ArmBuilds"
    secrets: inherit
