name: CD

on:
  push:
    branches: ["main"]
permissions:
  actions: write
  contents: read

jobs:
  build_and_publish_docker:
    uses: mikejgray/.github/.github/workflows/publish_docker.yml@patch-2
    secrets: inherit
